// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5E-qlgMXJsMpp2PXx2_IJHtfNWBVFnl4',
    appId: '1:534416205166:web:775944b9c2cf76cdaa0d7f',
    messagingSenderId: '534416205166',
    projectId: 'fcm-app-5aec2',
    authDomain: 'fcm-app-5aec2.firebaseapp.com',
    storageBucket: 'fcm-app-5aec2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9JWuyhW078BdXraCExSoon2_sazuQCw',
    appId: '1:534416205166:android:d03f7d28181ffd91aa0d7f',
    messagingSenderId: '534416205166',
    projectId: 'fcm-app-5aec2',
    storageBucket: 'fcm-app-5aec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtcTuFpsPBUAe1iTJf-HgHQMM7IzU3XI',
    appId: '1:534416205166:ios:39cb3ea4eaba1cc5aa0d7f',
    messagingSenderId: '534416205166',
    projectId: 'fcm-app-5aec2',
    storageBucket: 'fcm-app-5aec2.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtcTuFpsPBUAe1iTJf-HgHQMM7IzU3XI',
    appId: '1:534416205166:ios:39cb3ea4eaba1cc5aa0d7f',
    messagingSenderId: '534416205166',
    projectId: 'fcm-app-5aec2',
    storageBucket: 'fcm-app-5aec2.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5E-qlgMXJsMpp2PXx2_IJHtfNWBVFnl4',
    appId: '1:534416205166:web:f4ea0cc001f6aa4daa0d7f',
    messagingSenderId: '534416205166',
    projectId: 'fcm-app-5aec2',
    authDomain: 'fcm-app-5aec2.firebaseapp.com',
    storageBucket: 'fcm-app-5aec2.firebasestorage.app',
  );

}